apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: gourmet-greet

type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "216067"
  OPENAI_API_KEY: "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"