spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gourmetgreet@gmail.com
spring.mail.password=gelk oami rlpr ayyr
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#openai.api.key=${OPENAI_API_KEY}
openai.api.key=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